services:
  - type: web
    name: whatsapp-flask-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.index:app
    runtime: python
    plan: free
    region: oregon
    branch: main
    autoDeploy: true
